version: '3'

services:

  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: imersao-fullcycle-next-bank
    environment: 
      - NEXT_PUBLIC_NEST_API_URL=http://host.docker.internal:3000/api
      - NEXT_PUBLIC_BANK_NAME=BBX
      - NEXT_PUBLIC_BANK_CODE=001
    ports:
      - 3001:3000
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"